DeckBuilder.Card = DS.Model.extend
  name: DS.attr("string")
  manaCost: DS.attr("string")
  colors: DS.attr("string")
  rarity: DS.attr("string")
  power: DS.attr("number")
  toughness: DS.attr("number")
  dualCard: DS.attr("boolean")
  cardSetCode: DS.attr("string")
  type: DS.attr("string")
  supertype: DS.attr("string")
  typeClass: DS.attr("string")
  subtypes: DS.hasMany("subtype")
  keywordAbilities: DS.hasMany("keyword_ability")
  abilities: DS.hasMany("ability")
  
